adding another userful apps
flexcomng/erpnext_quick_install pull request #34
Opened 2024-10-08 16:51 UTC by linkmk

I just cloned HRMS code block to install another frappe apps like CRM, helpdesk and insights in this script.

2024-10-10 15:32 UTC, flexcomng commented
Hi! @linkmk Thanks for the contribution. I will test this addition and merge once completed.

2024-10-18 20:26 UTC, flexcomng requested changes

2024-10-18 20:26 UTC, flexcomng commented on README.md
Can you revert the repo name in the commit to the main?

2024-11-10 13:50 UTC, fthobe commented
@flexcomng that would actually be a cool addition. Can I just make the correct pull request?

2024-12-04 12:52 UTC, flexcomng commented
> @flexcomng that would actually be a cool addition. Can I just make the correct pull request?

@fthobe  yes please. I will close this pull request now so you can make the correct pull request.

2024-12-04 12:52 UTC, closed without merging

2024-12-04 13:31 UTC, fthobe commented
Have there been any significant changes we need to consider?

2024-12-04 13:34 UTC, flexcomng commented
No significant changes.

2024-12-04 14:55 UTC, fthobe commented
@flexcomng done in PR #40